import type { Metadata } from "next";
import "./globals.css";
import Blob from "@/components/Blob";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="dark font-heading bg-background">
				<Blob />
				{children}
			</body>
		</html>
	);
}
